"""Canonical pilot course catalog for Teonox.ai.

IDs in this file must match the IDs referenced by the LLM prompts.
"""

PILOT_COURSES = [
    {
        "id": "ai-baat-prompt-engg",
        "title": "AI se Baat Kaise Karte Hai",
        "subtitle": "Prompt Engineering for Everyone",
        "level": "Beginner",
        "duration": "4 weeks",
        "hours": 14,
        "price_inr": 2999,
        "original_price_inr": 4999,
        "language": "Hinglish",
        "summary": "Talk to AI like a pro. Frameworks for prompts that get real work done.",
        "outcomes": [
            "Master 7 prompt frameworks used in real jobs",
            "Build a personal prompt library you reuse daily",
            "Get the same task done 5x faster with AI",
        ],
        "modules": [
            "Why prompts matter (think like a manager, not a typist)",
            "The 7 frameworks: RACE, CRISP, RTF, COSTAR, CARE, BAB, PAS",
            "Long-context prompts: feed PDFs, sheets, code, websites",
            "Workflows: research, writing, summarising, comparing, deciding",
            "Your personal prompt library + Notion template",
        ],
        "audience": ["student", "professional", "business_owner", "parent"],
        "icon": "sparkles",
        "accent": "#FF6A00",
    },
    {
        "id": "ai-social-media-marketing",
        "title": "AI for Social Media Marketing",
        "subtitle": "Content, scheduling, hooks & analytics with AI",
        "level": "Beginner",
        "duration": "6 weeks",
        "hours": 22,
        "price_inr": 6999,
        "original_price_inr": 9999,
        "language": "Hinglish",
        "summary": "Automate captions, hooks, scheduling and reels research with AI agents.",
        "outcomes": [
            "Run 5 brand pages without burning out",
            "Build a content engine: hook \u2192 caption \u2192 schedule \u2192 analytics",
            "Save 15+ hours/week with reusable AI workflows",
        ],
        "modules": [
            "The new SMM operator role (AI does the typing, you decide)",
            "Hook mining + caption frameworks with Claude / GPT",
            "Reel research + script-to-shotlist pipeline",
            "Scheduling + auto-publishing stacks (Buffer/Make/Zapier + AI)",
            "Analytics: weekly report agent that writes itself",
            "Capstone: full brand calendar in 3 hours",
        ],
        "audience": ["professional", "business_owner", "student"],
        "icon": "megaphone",
        "accent": "#FF6A00",
    },
    {
        "id": "ai-branding",
        "title": "AI for Branding",
        "subtitle": "Brand voice, identity & assets with AI",
        "level": "Beginner",
        "duration": "5 weeks",
        "hours": 18,
        "price_inr": 5999,
        "original_price_inr": 8999,
        "language": "Hinglish",
        "summary": "Use AI to design brand voice, taglines, identity systems and assets fast.",
        "outcomes": [
            "Define a clear brand voice + style guide",
            "Generate identity directions in hours, not weeks",
            "Build a reusable brand kit with AI assets",
        ],
        "modules": [
            "Brand strategy basics for the AI era",
            "Voice + tone with AI: prompts that don\u2019t sound robotic",
            "Identity exploration with image models",
            "Logo refinement workflow (AI + Figma)",
            "Brand kit: templates, social, packaging mockups",
        ],
        "audience": ["business_owner", "professional", "student"],
        "icon": "palette",
        "accent": "#FF6A00",
    },
    {
        "id": "ai-ui-ux",
        "title": "AI for UI/UX",
        "subtitle": "Wireframes, prototypes & design systems with AI",
        "level": "Intermediate",
        "duration": "6 weeks",
        "hours": 24,
        "price_inr": 7999,
        "original_price_inr": 11999,
        "language": "Hinglish",
        "summary": "Ship beautiful UI with AI co-pilots, design systems and rapid prototypes.",
        "outcomes": [
            "Move from sketch \u2192 prototype 10x faster",
            "Use v0 / Cursor / Figma AI in real product flow",
            "Build a job-ready portfolio piece",
        ],
        "modules": [
            "The new designer role (orchestrator, not pixel-pusher)",
            "Wireframing with AI (briefs \u2192 layouts)",
            "Component-driven design systems",
            "Prototyping with v0 / Lovable / Bolt",
            "Hand-off + dev collaboration",
            "Portfolio capstone",
        ],
        "audience": ["student", "professional"],
        "icon": "layers",
        "accent": "#FF6A00",
    },
    {
        "id": "ai-digital-marketing",
        "title": "AI for Digital Marketing",
        "subtitle": "Funnels, ads, email & automations with AI",
        "level": "Intermediate",
        "duration": "8 weeks",
        "hours": 30,
        "price_inr": 9999,
        "original_price_inr": 14999,
        "language": "Hinglish",
        "summary": "Build complete marketing funnels powered by AI agents end-to-end.",
        "outcomes": [
            "Launch full-stack campaigns solo",
            "Run AI-assisted ads, email, landing pages",
            "Measure + optimise with AI analytics",
        ],
        "modules": [
            "Funnel-thinking for the AI era",
            "Landing pages with AI builders",
            "Email sequences: research \u2192 draft \u2192 personalise",
            "Ad creatives + variations with AI",
            "Analytics + AI weekly reporting",
            "Capstone: full funnel for a real product",
        ],
        "audience": ["professional", "business_owner"],
        "icon": "line-chart",
        "accent": "#FF6A00",
    },
    {
        "id": "ai-seo",
        "title": "AI for SEO",
        "subtitle": "Keyword, content, technical & topical authority",
        "level": "Intermediate",
        "duration": "6 weeks",
        "hours": 22,
        "price_inr": 7499,
        "original_price_inr": 10999,
        "language": "Hinglish",
        "summary": "Use AI to dominate SERPs with clustered content and on-page optimization.",
        "outcomes": [
            "Build topical authority clusters with AI",
            "Ship 5x more SEO content with quality",
            "Audit + fix technical SEO with AI assistants",
        ],
        "modules": [
            "SEO in the AI era (Google\u2019s new signals)",
            "Keyword + cluster research with AI",
            "Briefs \u2192 outlines \u2192 drafts \u2192 polish workflow",
            "On-page + entity SEO",
            "Technical SEO audits with AI",
            "GEO/AEO: optimising for AI search",
        ],
        "audience": ["professional", "business_owner"],
        "icon": "search",
        "accent": "#FF6A00",
    },
    {
        "id": "ai-in-depth-technical",
        "title": "AI in Depth (Technical)",
        "subtitle": "LLMs, RAG, agents & deployments",
        "level": "Advanced",
        "duration": "10 weeks",
        "hours": 40,
        "price_inr": 14999,
        "original_price_inr": 19999,
        "language": "English + Hinglish",
        "summary": "Go technical: LLMs, RAG, fine-tuning, agentic systems and production.",
        "outcomes": [
            "Build and ship LLM apps that scale",
            "Design agents + RAG systems with proper guardrails",
            "Deploy + observe AI features in production",
        ],
        "modules": [
            "How LLMs really work (intuition, not math overload)",
            "Prompting at scale + structured outputs",
            "RAG: chunking, embeddings, retrieval quality",
            "Agents + tool-use patterns",
            "Evals + safety",
            "Deployment + observability",
            "Capstone: ship a production AI feature",
        ],
        "audience": ["professional", "student"],
        "icon": "cpu",
        "accent": "#FF6A00",
    },
]

COURSE_IDS = [c["id"] for c in PILOT_COURSES]

COURSE_CATALOG_TEXT = "\n".join(
    f"- {c['id']}: {c['title']} \u2014 {c['subtitle']} ({c['level']}). {c['summary']}"
    for c in PILOT_COURSES
)
